---

- name: Run show commands routers
  hosts: cisco-routers
  gather_facts: false

  tasks:

    - name: run sh run
      raw: sh run
      register: sh_run
      
    - local_action: copy content={{ sh_run }} dest=/software/ansible/cisco/routers_shrun

    - name: run sh int
      raw: sh int
      register: sh_int
      
    - local_action: copy content={{ sh_int }} dest=/software/ansible/cisco/routers_shint

    - name: run sh ip route
      raw: sh ip route
      register: sh_ip_route
      
    - local_action: copy content={{ sh_ip_route }} dest=/software/ansible/cisco/routers_shrout
	  
    - name: run sh access-lists
      raw: sh access-lists
      register: sh_acl
      
    - local_action: copy content={{ sh_acl }} dest=/software/ansible/cisco/routers_shacl

- name: Run show commands switches
  hosts: cisco-switches
  gather_facts: false

  tasks:

    - name: run sh run
      raw: sh run
      register: sh_run_sw
      
    - local_action: copy content={{ sh_run_sw }} dest=/software/ansible/cisco/switches_shrun

    - name: run sh int status
      raw: sh int status
      register: sh_int_sw
      
    - local_action: copy content={{ sh_int_sw }} dest=/software/ansible/cisco/switches_int

    - name: run sh vlan
      raw: show vlan
      register: sh_vlan
      
    - local_action: copy content={{ sh_vlan }} dest=/software/ansible/cisco/switches_vlan
	  
    - name: run sh int trunk
      raw: sh int trunk
      register: sh_trunk
      
    - local_action: copy content={{ sh_trunk }} dest=/software/ansible/cisco/switches_trunk
	  